// (c) Eduardo Doria Lima
// SPDX-License-Identifier: MIT

#include "DoriaxWin.h"

#include "GamepadWin.h"
#include "SystemWin.h"
#include "WinInputRouter.h"
#include "WindowWin.h"

#if defined(SOKOL_VULKAN)
// After WindowWin.h: the Win32 surface entry points come from <windows.h>
#include "VulkanContext.h"
#elif defined(SOKOL_D3D11)
#include "D3D11Context.h"
#endif

#include "Engine.h"

#include <cstdio>

#ifndef DORIAX_VSYNC_ENABLED
#define DORIAX_VSYNC_ENABLED 1
#endif

// 0 = windowed, 1 = maximized, 2 = fullscreen
#ifndef DORIAX_WINDOW_MODE
#define DORIAX_WINDOW_MODE 0
#endif

#ifndef DORIAX_WINDOW_RESIZABLE
#define DORIAX_WINDOW_RESIZABLE 1
#endif

#ifndef DORIAX_WINDOW_TITLE
#define DORIAX_WINDOW_TITLE "Doriax"
#endif

#ifdef DORIAX_WINDOW_ICON
// Generated by the editor export into the project root (on the include path)
#include "app_icon.h"
#endif

using namespace doriax;

namespace {

constexpr wchar_t WINDOW_CLASS_NAME[] = L"DoriaxGameWindow";

#if defined(SOKOL_GLCORE)
// wglCreateContextAttribsARB / wglSwapIntervalEXT, resolved at runtime
using CreateContextAttribsProc = HGLRC (WINAPI*)(HDC, HGLRC, const int*);
using SwapIntervalProc = BOOL (WINAPI*)(int);

constexpr int WGL_CONTEXT_MAJOR_VERSION = 0x2091;
constexpr int WGL_CONTEXT_MINOR_VERSION = 0x2092;
constexpr int WGL_CONTEXT_PROFILE_MASK = 0x9126;
constexpr int WGL_CONTEXT_CORE_PROFILE_BIT = 0x00000001;

HDC deviceContext = nullptr;
HGLRC glContext = nullptr;
SwapIntervalProc swapIntervalEXT = nullptr;
#endif

GamepadWin gamepads;
WinInputRouter inputRouter;

bool shouldClose = false;

#if defined(SOKOL_GLCORE)
template <typename T>
T wglProc(const char* name) {
    PROC address = wglGetProcAddress(name);
    if (!address || address == reinterpret_cast<PROC>(1) ||
        address == reinterpret_cast<PROC>(2) ||
        address == reinterpret_cast<PROC>(3) ||
        address == reinterpret_cast<PROC>(-1))
        return nullptr;
    return reinterpret_cast<T>(address);
}
#endif

LRESULT CALLBACK windowProc(HWND handle, UINT message,
                            WPARAM wParam, LPARAM lParam) {
    switch (message) {
        case WM_CLOSE:
            shouldClose = true;
            return 0;
        case WM_DESTROY:
            PostQuitMessage(0);
            return 0;
        case WM_ERASEBKGND:
            return 1;
        case WM_SIZE:
            WindowWin::refreshClientSize();
            WindowWin::updateCursorClip();
            return 0;
        case WM_MOVE:
        case WM_DISPLAYCHANGE:
        case WM_SETFOCUS:
            WindowWin::updateCursorClip();
            break;
        case WM_KILLFOCUS:
            WindowWin::handleFocusLost();
            break;
        case WM_SETCURSOR:
            if (LOWORD(lParam) == HTCLIENT && WindowWin::isCursorHidden()) {
                SetCursor(nullptr);
                return TRUE;
            }
            break;
        default:
            break;
    }

    LRESULT result = 0;
    if (inputRouter.handleMessage(handle, message, wParam, lParam, result))
        return result;

    return DefWindowProcW(handle, message, wParam, lParam);
}

#if defined(SOKOL_VULKAN)

VkResult createWindowSurface(VkInstance instance, VkSurfaceKHR* surface) {
    VkWin32SurfaceCreateInfoKHR surfaceInfo{};
    surfaceInfo.sType = VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR;
    surfaceInfo.hinstance = WindowWin::instance();
    surfaceInfo.hwnd = WindowWin::handle();
    return vkCreateWin32SurfaceKHR(instance, &surfaceInfo, nullptr, surface);
}

bool createContext() {
    VulkanContextConfig config;
    config.surfaceExtension = VK_KHR_WIN32_SURFACE_EXTENSION_NAME;
    config.createSurface = createWindowSurface;
    config.vsync = DORIAX_VSYNC_ENABLED != 0;
    return VulkanContext::create(config);
}

void destroyContext() {
    VulkanContext::destroy();
}

void beginFrame() {
    VulkanContext::beginFrame();
}

void endFrame() {
    VulkanContext::endFrame();
}

#elif defined(SOKOL_D3D11)

bool createContext() {
    D3D11ContextConfig config;
    config.vsync = DORIAX_VSYNC_ENABLED != 0;
    return D3D11Context::create(config);
}

void destroyContext() {
    D3D11Context::destroy();
}

void beginFrame() {
    D3D11Context::beginFrame();
}

void endFrame() {
    D3D11Context::endFrame();
}

#else

bool createContext() {
    deviceContext = GetDC(WindowWin::handle());
    if (!deviceContext) {
        std::fprintf(stderr, "Error: Could not acquire the OpenGL device context.\n");
        return false;
    }

    PIXELFORMATDESCRIPTOR descriptor{};
    descriptor.nSize = sizeof(descriptor);
    descriptor.nVersion = 1;
    descriptor.dwFlags = PFD_DRAW_TO_WINDOW | PFD_SUPPORT_OPENGL | PFD_DOUBLEBUFFER;
    descriptor.iPixelType = PFD_TYPE_RGBA;
    descriptor.cColorBits = 32;
    descriptor.cDepthBits = 24;
    descriptor.cStencilBits = 8;

    const int pixelFormat = ChoosePixelFormat(deviceContext, &descriptor);
    if (!pixelFormat || !SetPixelFormat(deviceContext, pixelFormat, &descriptor)) {
        std::fprintf(stderr, "Error: No OpenGL pixel format available.\n");
        return false;
    }

    // wglCreateContextAttribsARB is only reachable through a current context
    HGLRC legacy = wglCreateContext(deviceContext);
    if (!legacy) {
        std::fprintf(stderr, "Error: Could not create an OpenGL context.\n");
        return false;
    }
    if (!wglMakeCurrent(deviceContext, legacy)) {
        wglDeleteContext(legacy);
        std::fprintf(stderr, "Error: Could not activate the OpenGL context.\n");
        return false;
    }

    auto createContextAttribs = wglProc<CreateContextAttribsProc>(
        "wglCreateContextAttribsARB");
    if (createContextAttribs) {
        const int attributes[] = {
            WGL_CONTEXT_MAJOR_VERSION, 4,
            WGL_CONTEXT_MINOR_VERSION, 1,
            WGL_CONTEXT_PROFILE_MASK, WGL_CONTEXT_CORE_PROFILE_BIT,
            0
        };
        glContext = createContextAttribs(deviceContext, nullptr, attributes);
    }
    wglMakeCurrent(nullptr, nullptr);
    wglDeleteContext(legacy);

    if (!glContext) {
        std::fprintf(stderr, "Error: Could not create an OpenGL 4.1 core context.\n");
        return false;
    }
    if (!wglMakeCurrent(deviceContext, glContext)) {
        std::fprintf(stderr, "Error: Could not activate the OpenGL 4.1 context.\n");
        return false;
    }

    swapIntervalEXT = wglProc<SwapIntervalProc>("wglSwapIntervalEXT");
    if (swapIntervalEXT) swapIntervalEXT(DORIAX_VSYNC_ENABLED ? 1 : 0);
    return true;
}

void destroyContext() {
    if (glContext) {
        wglMakeCurrent(nullptr, nullptr);
        wglDeleteContext(glContext);
        glContext = nullptr;
    }
    if (deviceContext) {
        ReleaseDC(WindowWin::handle(), deviceContext);
        deviceContext = nullptr;
    }
    swapIntervalEXT = nullptr;
}

void beginFrame() {
}

void endFrame() {
    SwapBuffers(deviceContext);
}

#endif

}

int DoriaxWin::init(int argc, char **argv) {
    Engine::systemInit(argc, argv, new SystemWin(&inputRouter));

    WindowWinConfig config;
    config.title = DORIAX_WINDOW_TITLE;
    config.width = DEFAULT_WINDOW_WIDTH;
    config.height = DEFAULT_WINDOW_HEIGHT;
    config.resizable = DORIAX_WINDOW_RESIZABLE;
    config.maximized = (DORIAX_WINDOW_MODE == 1);
    config.windowProc = windowProc;
    config.className = WINDOW_CLASS_NAME;
#ifdef DORIAX_WINDOW_ICON
    // The executable icon comes from app_icon.rc; this is the window and
    // taskbar icon.
    config.icon = static_cast<HICON>(LoadImageW(
        GetModuleHandleW(nullptr), MAKEINTRESOURCEW(1), IMAGE_ICON, 0, 0,
        LR_DEFAULTSIZE | LR_SHARED));
#endif

    WindowWin::setClientSizeCallback([](int, int) {
        Engine::systemViewChanged();
    });

    if (!WindowWin::create(config))
        return -1;
    WindowWin::show(config.maximized);

    if (!createContext()) {
        destroyContext();
        WindowWin::destroy();
        return -1;
    }

    gamepads.init();

    Engine::systemViewLoaded();
    Engine::systemViewChanged();

    if (DORIAX_WINDOW_MODE == 2)
        WindowWin::requestFullscreen();

    while (!shouldClose) {
        MSG message{};
        while (PeekMessageW(&message, nullptr, 0, 0, PM_REMOVE)) {
            if (message.message == WM_QUIT) {
                shouldClose = true;
                break;
            }
            TranslateMessage(&message);
            DispatchMessageW(&message);
        }
        if (shouldClose)
            break;

        gamepads.poll();

        beginFrame();
        Engine::systemDraw();
        endFrame();
    }

    Engine::systemViewDestroyed();
    Engine::systemShutdown();

    gamepads.shutdown();
    destroyContext();
    WindowWin::destroy();
    return 0;
}
